Repository Root-App/root-eslint-plugin, pull requests merged in 2020-09, with the labels that each got.

#35 [Detox e2e] Update valid-test-filesnames to accept multiple suffixes
  lib/rules/valid-test-filenames.js
  test/lib/rules/valid-test-filenames-test.js
Labels: react-guild, reviewed, team-market-expansion

#36 animated lint
  lib/rules/use-native-driver.js
  test/lib/rules/use-native-driver-test.js
Labels: ready-for-review, team-productivity-client

#38 Adds eslint rules for async before hooks
  lib/configs/recommended.js
  lib/rules/prevent-async-before-all-without-before-all-slowly.js
  lib/rules/prevent-async-before-each-without-before-each-slowly.js
  test/lib/rules/prevent-async-before-all-without-before-all-slowly-test.js
  test/lib/rules/prevent-async-before-each-without-before-each-slowly-test.js
Labels: react-guild, ready-for-review, team-partner-platform
